#pragma once

// Version information - automatically generated by CMake
#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define BUILD_NUMBER 0
#define VERSION_STRING "1.0.0.0"

// Build type
#define DEBUG_BUILD 0
